#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Z-Wave Interpreter - Constants © Autolog 2020-2022
#

# plugin Constants

try:
    # noinspection PyUnresolvedReferences
    import indigo
except ImportError:
    pass

K_ADDRESS = 1
K_API_VERSION = 2
K_PATH = 3
K_PLUGIN_DISPLAY_NAME = 4
K_PLUGIN_ID = 5
K_PLUGIN_INFO = 6
K_PLUGIN_VERSION = 7
K_ZWI = 8
K_ZWAVE_LOGGING = 9
K_ZWAVE_LOGGING_FOLDER = 10
K_ZWAVE_LOGGING_FILE_NAME = 11
K_ZWAVE_LOGGING_MODE = 12
K_INTERPRETER_CLASS_INSTANCE = 13
K_ZWAVE_LOG_TO_INDIGO_EVENT_LOG = 14
K_ZWAVE_LOGGING_AUTO_START = 15
K_PLUGIN_PREFS = 16

K_LOG_LEVEL_NOT_SET = 0
K_LOG_LEVEL_DEBUGGING = 5
K_LOG_LEVEL_ZWAVE = 10
K_LOG_LEVEL_INFO = 20
K_LOG_LEVEL_WARNING = 30
K_LOG_LEVEL_ERROR = 40
K_LOG_LEVEL_CRITICAL = 50

K_LOG_LEVEL_TRANSLATION = dict()
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_NOT_SET] = u"Not Set"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_DEBUGGING] = u"Debugging"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_ZWAVE] = u"Z-Wave Logging"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_INFO] = u"No Z-Wave Logging"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_WARNING] = u"Warning"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_ERROR] = u"Error"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_CRITICAL] = u"Critical"
