#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Z-Wave Interpreter - Constants © Autolog 2020
#

# Z-Wave Command Classes constants


ZW_BASIC_COMMAND = 0X20
ZW_SWITCH_BINARY = 0X25
ZW_SWITCH_MULTILEVEL = 0x26
ZW_SENSOR_BINARY = 0x30
ZW_SENSOR_MULTILEVEL = 0x31
ZW_METER = 0x32
ZW_THERMOSTAT_MODE = 0x40
ZW_THERMOSTAT_OPERATING_STATE = 0x42  # Added in Plugin Version 0.4.4
ZW_THERMOSTAT_SETPOINT = 0x43
ZW_THERMOSTAT_FAN_MODE = 0x44  # Added in Plugin Version 0.4.4
ZW_THERMOSTAT_FAN_STATE = 0x45  # Added in Plugin Version 0.4.4
ZW_CLIMATE_CONTROL_SCHEDULE = 0x46
ZW_CENTRAL_SCENE = 0x5B
ZW_MULTI_CHANNEL = 0x60
ZW_NOTIFICATION = 0x71
ZW_BATTERY = 0x80
ZW_WAKE_UP = 0x84
ZW_SENSOR_ALARM = 0x9C
