#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Z-Wave Interpreter - Constants © Autolog 2020
#

# Z-Wave Interpreter common constants

# Z-Wave Command Classes and ZW_COMMANDS

# ### Shared Constants ###

ZW_BATTERY_LEVEL = 1
ZW_BATTERY_LEVEL_UI = 2
ZW_COMMAND = 4
ZW_COMMAND_BYTES = 5
ZW_COMMAND_BYTES_UI = 6
ZW_COMMAND_CLASS_UI = 8
ZW_COMMAND_CLASS_VERSION = 9
ZW_COMMAND_CLASS_VERSION_UI = 10
ZW_COMMAND_DETAIL = 11
ZW_COMMAND_PACKET_LENGTH = 12
ZW_COMMAND_UI = 13
ZW_ENDPOINT = 15
ZW_ERROR_MESSAGE = 16
ZW_INTERPRETATION_ATTEMPTED = 21
ZW_INTERPRETATION_DETAIL_UI = 22
ZW_INTERPRETATION_OVERVIEW_UI = 23
ZW_INTERPRETATION_UI = 24
ZW_INTERPRETED = 25
ZW_MANUFACTURER_FIELDS = 26
ZW_METER_TYPE = 27
ZW_METER_TYPE_UI = 28
ZW_MODE = 29
ZW_MODE_UI = 30
ZW_NODE_ID = 31
ZW_NUMBER_OF_MANUFACTURER_FIELDS = 32
ZW_PRECISION = 33
ZW_SCALE_UI = 34
ZW_SCALE_UI_COMPACT = 35
ZW_SCALES = 36
ZW_SENSOR_ALARM_TYPE = 37
ZW_SENSOR_ALARM_TYPE_UI = 38
ZW_SENSOR_TYPE = 39
ZW_SENSOR_TYPE_UI = 40
ZW_SETPOINT_TYPE = 41
ZW_SETPOINT_TYPE_UI = 42
ZW_SETPOINT_TYPES = 43
ZW_SIZE = 44
ZW_VALUE = 45
ZW_VALUE_BOOL = 46
ZW_VALUE_UI = 47
#
ZW_SECONDS = 48
ZW_COMMAND_SUCCESS = 49
ZW_TIME_DELTA = 50

ZW_SEQUENCE_NUMBER = 51
ZW_KEY_ATTRIBUTES = 52
ZW_KEY_ATTRIBUTES_UI = 53
ZW_SCENE_NUMBER = 54
ZW_INDIGO_DEVICE = 55

ZW_OPERATING_STATE = 56
ZW_OPERATING_STATE_UI = 57
ZW_FAN_MODE = 58
ZW_FAN_MODE_UI = 59
